### Get Orders

GET http://localhost:4004/odata/v4/manage-orders/Orders

### Get Order
GET http://localhost:4004/odata/v4/manage-orders/Orders('client3@client3.com')

### Create Orders
POST http://localhost:4004/odata/v4/manage-orders/Orders HTTP/1.1
Content-Type: application/json

{
                    "ClientEmail": "client5@client5.com",
                    "FirstName": "Lorena",
                    "LastName": "García",
                    "CreatedOn": "2024-10-10",
                    "Reviewed": false,
                    "Approved": false,
                    "Country_code": "ES",
                    "Status": ""
}

### Update Orders
PUT http://localhost:4004/odata/v4/manage-orders/Orders('client22@client1.com') HTTP/1.1
Content-Type: application/json

{
                    "FirstName": "Updated",
                    "LastName": "Updated"
}

### DELETE Orders
DELETE http://localhost:4004/odata/v4/manage-orders/Orders('client5@client5.com') HTTP/1.1

### Get Customer Rate - FUNCTION
GET http://localhost:4004/odata/v4/manage-orders/getClientTaxRate(ClientEmail='client2@client2.com') HTTP/1.1

### Cancel Order - ACTION
POST http://localhost:4004/odata/v4/manage-orders/cancelOrder HTTP/1.1
Content-Type: application/json

{"ClientEmail" : "client2@client2.com"}

### Get Customer Rate - FUNCTION BOUND
GET http://localhost:4004/odata/v4/manage-orders/Orders('client2@client2.com')/ManageOrders.getClientTaxRate(ClientEmail='client2@client2.com') HTTP/1.1

### Cancel Order - ACTION BOUND
POST http://localhost:4004/odata/v4/manage-orders/Orders('client2@client2.com')/ManageOrders.cancelOrder HTTP/1.1
Content-Type: application/json

{"ClientEmail" : "client2@client2.com"}


### Get Incidents

GET http://localhost:4004/odata/v4/sapbackend-exit/Incidents


### Graphql
https://port4004-workspaces-ws-jznwh.us10.trial.applicationstudio.cloud.sap/graphql
